Cookie manager
bob-collective/ui pull request #295
Opened 2024-11-11 14:30 UTC by slavastartsev

2024-11-14 09:43 UTC, danielsimao requested changes

2024-11-14 09:43 UTC, danielsimao commented on apps/bob-pay/src/types/image.d.ts
> +declare module '*.jpg';
remove these in favor of what I pushed to main

2024-11-14 09:45 UTC, slavastartsev commented on apps/bob-pay/src/types/image.d.ts
> +declare module '*.jpg';
> remove these in favor of what I pushed to main

Sure, this will be removed once I resolve merge conflicts

2024-12-10 14:45 UTC, slavastartsev commented on apps/evm/src/components/Layout/Sidebar.tsx
> +                href='https://docs.google.com/document/d/1D00oItKIz7QXjXom07UAaMnz4mov80ld/edit'
this link will be updated

2024-12-10 15:20 UTC, tomjeatt approved these changes

2024-12-10 15:20 UTC, tomjeatt commented on apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> +          const connectData = await connectAsync({
Not a change request, but wondering why this change is needed?

2024-12-10 16:12 UTC, tomjeatt commented on apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> +          sendGTMEvent({ event: 'evm-conenct', address: connectData.accounts });
Typo here 
```suggestion
          sendGTMEvent({ event: 'evm-connect', address: connectData.accounts });
```

2024-12-10 16:13 UTC, tomjeatt commented on apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> +          const connectData = await connectAsync({
Got it—thanks.

2024-12-10 16:13 UTC, tomjeatt commented on apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> +          sendGTMEvent({ event: 'btc-conenct', address: btcAddress.address });
```suggestion
          sendGTMEvent({ event: 'btc-connect', address: btcAddress.address });
```

2024-12-10 16:13 UTC, slavastartsev commented on apps/evm/src/connect-ui/component/ConnectModal/ConnectModal.tsx
> +          sendGTMEvent({ event: 'btc-conenct', address: btcAddress.address });
eagle eye

2024-12-10 17:24 UTC, merged