Stake update
bob-collective/ui pull request #327
Opened 2024-12-03 11:14 UTC by tomjeatt

2024-12-04 13:33 UTC, danielsimao requested changes

2024-12-04 13:33 UTC, danielsimao commented on apps/evm/src/app/[lang]/(bridge)/components/StatusChip/StatusChip.style.tsx
> +  height: 32px;
Is this needed?

2024-12-04 13:39 UTC, slavastartsev commented on apps/evm/src/app/[lang]/(bridge)/utils/stakeData.tsx
> +    incentives: [Incentives.pell, Incentives.beckrock, Incentives.babylon],
```suggestion
    incentives: [Incentives.pell, Incentives.bedrock, Incentives.babylon],
```

2024-12-04 13:40 UTC, slavastartsev commented on apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
> +  beckrock,
```suggestion
  bedrock,
```

2024-12-04 13:46 UTC, slavastartsev commented on apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
> +  const sortedStrategies = strategies.sort((a, b) => (b?.tvl || 0) - (a?.tvl || 0));
might be good for `useMemo`. e.g. [... strategies].sort()

2024-12-04 13:47 UTC, slavastartsev commented on apps/evm/src/app/[lang]/(bridge)/stake/components/StakeTable/StakeTable.tsx
> +  const rows: StakeTableRow[] = sortedStrategies.map((strategy, idx) => {
Would be good to memo this array of rows

2024-12-04 13:50 UTC, slavastartsev commented on apps/evm/src/app/[lang]/(bridge)/utils/stakeData.tsx
> +export type StakingInfo = Record<string, (typeof stakingInfo)[keyof typeof stakingInfo] | undefined>;
`import { ValueOf } from 'viem';`

```suggestion
export type StakingInfo = Record<string, ValueOf<typeof stakingInfo> | undefined>;
```

2024-12-04 16:14 UTC, tomjeatt commented on apps/evm/src/app/[lang]/(bridge)/components/StatusChip/StatusChip.style.tsx
> +  height: 32px;
No, good spot—that was from a version where I tried a variant on the transaction list (that I backed out). Will revert.

2024-12-04 16:16 UTC, tomjeatt commented on apps/evm/src/app/[lang]/(bridge)/stake/components/StrategyModal/StrategyModal.tsx
> +import { StyledCard, StyledFlex } from '../../Stake.style';
Good idea—done

2024-12-05 09:08 UTC, danielsimao requested changes

2024-12-05 09:08 UTC, danielsimao commented on apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
> +  '0xdf3aa56f2626e253b5db7703ac7241e835140566': '0x6f0AfADE16BFD2E7f5515634f2D0E3cd03C845Ef',
Make sure these addresses are checksummed 

https://ethsum.netlify.app/

2024-12-05 09:08 UTC, danielsimao commented on apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
> +              address: seTokenContractDataCalls?.[strategy.raw.outputToken?.symbol]?.[2] as Address,
What does `se` in `seTokenContractDataCalls` stand for?

2024-12-05 09:08 UTC, danielsimao commented on apps/evm/src/components/Chain/Chain.tsx
> +  label?: boolean;
`hideLabel` 

because this:

`<Chain hideLabel/>` is better than `<Chain label={false} />`

2024-12-05 09:08 UTC, danielsimao commented on apps/evm/src/lib/wagmi/config.ts
> +const prodChains = [bob, mainnet];
necessary change?

2024-12-05 11:43 UTC, tomjeatt commented on apps/evm/src/lib/wagmi/config.ts
> +const prodChains = [bob, mainnet];
yes—if we have it this way round, the TVL is displayed without a wallet connected.

2024-12-05 11:46 UTC, tomjeatt commented on apps/evm/src/components/Chain/Chain.tsx
> +  label?: boolean;
This change can be reverted actually—this prop is not being used anywhere

2024-12-05 11:51 UTC, tomjeatt commented on apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
> +  '0xdf3aa56f2626e253b5db7703ac7241e835140566': '0x6f0AfADE16BFD2E7f5515634f2D0E3cd03C845Ef',
Done :)

2024-12-05 11:51 UTC, tomjeatt commented on apps/evm/src/app/[lang]/(bridge)/stake/hooks/useGetStakingStrategies.ts
> +              address: seTokenContractDataCalls?.[strategy.raw.outputToken?.symbol]?.[2] as Address,
segment—that's how they prefix things (e.g. seUNITBTC)

2024-12-05 11:55 UTC, danielsimao approved these changes

2024-12-05 14:50 UTC, merged